name: HTTP APP WORKFLOW
on:
  push:
    branches: [ main ]
  
jobs:
  test_and_build:
  runs-on: ubuntu-latest
    steps:
    - name: clone code
      uses: actions/checkout@v2
    
    -name : setup node js
      uses: actions/setup-node@v6
      with:
        node-version: '24'  
    
    - name: install node js packages
      run: npm install

   #  - name: run tests
   #   run: npm test

    - name: build app
       run: npm run build

 